---
- name: Fetch latest opt-local archive
  copy: src="{{ builder.archive.dir }}/local-latest.tar.gz" dest=/var/tmp/local.tar.gz

- name: Replace /opt/local with contents of local.tar.gz
  shell: |
    mv /opt/local /opt/local.old
    /usr/bin/gtar -xzf /var/tmp/local.tar.gz -C /
