#!/bin/bash

ZPOOL=/usr/sbin/zpool

POOLS=($(${ZPOOL} list -Ho name))
POOL_COUNT=${#POOLS[@]}

i=0

echo -e "{\n\t\"data\": ["

for pool in ${POOLS[@]}; do 
	i=$(($i+1))
	
	if [ ${i} -ne ${POOL_COUNT} ]; then
		echo -e "\t\t{ \"{#ZPOOL}\": \"${pool}\" },"
	else
		echo -e "\t\t{ \"{#ZPOOL}\": \"${pool}\" }"
	fi
done

echo -e "\t]\n}"
