---
- name: Create /usr/sbin/rc-scripts.sh
  copy: src=rc-scripts.sh dest=/usr/sbin/rc-scripts.sh owner=root group=root mode=0750

- name: Create /var/lib/rc-scripts
  file: path=/var/lib/rc-scripts state=directory owner=root group=root mode=0755

- name: Create /var/lib/rc-scripts/99-alldone.sh
  copy: src=99-alldone.sh dest=/var/lib/rc-scripts/99-alldone.sh owner=root group=root mode=0755

- name: Create rc-scripts systemd service file
  template: src=rc-scripts.service.j2 dest=/etc/systemd/system/rc-scripts.service owner=root group=root mode=0644

- name: Enable rc-scripts systemd service
  shell: systemctl enable rc-scripts.service
