---
- name: Create /usr/sbin/rc-scripts.sh
  copy: src=rc-scripts.sh dest=/usr/sbin/rc-scripts.sh owner=root group=root mode=0750

- name: Create /var/lib/rc-scripts
  file: path=/var/lib/rc-scripts state=directory owner=root group=root mode=0755

- name: Create /var/lib/rc-scripts/99-alldone.sh
  copy: src=99-alldone.sh dest=/var/lib/rc-scripts/99-alldone.sh owner=root group=root mode=0755

- name: Install jq (for parsing sdc:nics mdata)
  yum: name=jq state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: Install jq (for parsing sdc:nics mdata)
  dnf: name=jq state=present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: Create /var/lib/rc-scripts/04-mtu-set.sh
  copy: src=04-mtu-set.sh dest=/var/lib/rc-scripts/04-mtu-set.sh owner=root group=root mode=0755

- name: Create rc-scripts systemd service file
  template: src=rc-scripts.service.j2 dest=/etc/systemd/system/rc-scripts.service owner=root group=root mode=0644

- name: Enable rc-scripts systemd service
  shell: systemctl enable rc-scripts.service

- name: Fix /etc/rc.d/rc.local permissions
  file: dest=/etc/rc.d/rc.local mode=u+x
