---
- name: Check OS type/version
  fail: msg="Invalid OS distribution type/version"
  when: ansible_distribution != "CentOS" or ansible_distribution_major_version != "7"

- name: Install Zabbix repository package
  yum: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm state=present

- name: Install Zabbix server packages
  yum: name={{ item }} state=present
  with_items:
    - zabbix-server-pgsql
    - zabbix-web-pgsql
    - zabbix-get
    - httpd
    - mod_ssl
    - php-opcache
    - libsemanage-python

- name: Get Zabbix server version
  shell: rpm -q --queryformat "%{VERSION}" zabbix-server-pgsql
  register: zabbix_server_package

- name: Import Zabbix database schema
  shell: zcat "/usr/share/doc/zabbix-server-pgsql-{{ zabbix_server_package.stdout }}/create.sql.gz" | psql -U "{{ zabbix_db_user }}" -d "{{ zabbix_db_name }}"
  environment:
    PGPASSWORD: "{{ zabbix_db_password }}"

- name: Modify PHP configuration for Zabbix
  ini_file: dest=/etc/php.ini
            section="{{ item.section | default('PHP') }}"
            option="{{ item.option }}"
            value="{{ item.value }}"
  with_items:
    - { option: max_execution_time,     value: 300 }
    - { option: memory_limit,           value: 128M }
    - { option: post_max_size,          value: 16M }
    - { option: upload_max_filesize,    value: 2M }
    - { option: max_input_time,         value: 300 }
    - { option: date.timezone,          value: UTC, section: Date }

- name: Update /etc/zabbix/zabbix_server.conf
  lineinfile: dest="/etc/zabbix/zabbix_server.conf"
              regexp="{{ item.regexp }}"
              line="{{ item.line }}"
  with_items:
    - { regexp: "^DBHost=", line: "DBHost={{ zbx_server_DBHost }}" }
    - { regexp: "^DBName=", line: "DBName={{ zbx_server_DBName }}" }
    - { regexp: "^DBUser=", line: "DBUser={{ zbx_server_DBUser }}" }
    - { regexp: "^DBPassword=", line: "DBPassword={{ zbx_server_DBPassword }}" }
    - { regexp: "^DBPort=", line: "DBPort={{ zbx_server_DBPort }}" }

- name: Create /etc/zabbix/web/zabbix.conf.php
  template: src=zabbix.conf.php.j2
            dest=/etc/zabbix/web/zabbix.conf.php
            mode=0640
            owner=apache
            group=apache

- name: Change default DocumentRoot in /etc/httpd/conf/httpd.conf
  lineinfile: dest="/etc/httpd/conf/httpd.conf"
              regexp='^DocumentRoot'
              line='DocumentRoot "/usr/share/zabbix"'

- name: Create externalscripts and alertscripts symlinks in /etc/zabbix
  file: src="/usr/lib/zabbix/{{ item }}"
        dest="/etc/zabbix/{{ item }}"
        state=link
  with_items:
    - alertscripts
    - externalscripts

- name: SELinux configuration
  seboolean: name={{ item.name }} state={{ item.state }} persistent={{ item.persist }}
  with_items:
#    - { name: httpd_can_connect_zabbix, state: yes, persist: yes }
    - { name: httpd_can_network_connect_db, state: yes, persist: yes }
    - { name: zabbix_can_network, state: yes, persist: yes }
    - { name: httpd_can_network_connect, state: yes, persist: yes }

- name: Ensure that services are enabled and running
  service: name={{ item }} state=started enabled=yes
  with_items:
    - httpd
    - zabbix-server
