---
- name: Update packages (CentOS)
  shell: yum update --security
  when: ansible_distribution == "CentOS"

- name: Update packages (SmartOS)
  shell: pkgin -f update && pkgin -y upgrade
  when: ansible_distribution == "SmartOS"

- name: Install common packages (CentOS)
  yum: name={{ item }} state=latest
  with_items:
    - libselinux-python
    - tcpdump
    - screen
    - bind-utils
    - openssh-clients
    - strace
    - vim-enhanced
    - bash-completion
  when: ansible_distribution == "CentOS"
