#!/bin/bash

. /lib/svc/share/smf_include.sh

CMD="${1}"
STAGE="${2}"

if [[ -z "${CMD}" || -z "${STAGE}" ]]; then
    echo "Usage:   $0 <cmd> <stage>"
    echo "Example: $0 start pre-network"
    exit $SMF_EXIT_ERR_CONFIG
fi

if ! [[ "${CMD}" =~ ^start$|^stop$|^restart$|^refresh$ ]]; then
    echo "Unknown command: ${CMD}."
    echo "Allowed commands: start, stop, restart, refresh."
    exit $SMF_EXIT_ERR_CONFIG
fi

STAGE_DIR="/opt/custom/method/rc.d-${STAGE}"
if [[ ! -d "${STAGE_DIR}" ]]; then
    echo "Directory ${STAGE_DIR} does not exist. Exiting."
    exit $SMF_EXIT_ERR_FATAL
fi

# run RC files in reverse order if stopping
if [[ "${CMD}" == "stop" ]]; then
    REVERSE_LIST="-r"
else
    REVERSE_LIST=""
fi

# get list of all .sh files in STAGE_DIR
FILE_LIST="$(ls -1 ${REVERSE_LIST} ${STAGE_DIR}/*.sh 2> /dev/null)"

if [[ -z "${FILE_LIST}" ]]; then
    # nothing to do
    exit $SMF_EXIT_OK
fi

# verify if a script is executable and run it
while read runscript; do
    if [[ -x "${runscript}" ]]; then
        echo "Running rc file: ${runscript}"
        if ! "${runscript}" "${CMD}"; then
            echo "Error running ${runscript}!"
        fi
    else
        echo "Script ${runscript} is not executable. Ignoring."
    fi
done <<< "${FILE_LIST}"

exit $SMF_EXIT_OK
