#!/usr/perl5/bin/perl

use strict;
use warnings;

my $interval = 10;

my $data = undef;

my $date;

open(KVMIOSTAT, "/opt/zabbix/etc/scripts/kvmiostat -r -b $interval |") || die "Failed to execute kvmiostat: $!\n";

while(my $line = <KVMIOSTAT>) {

	# We are ready to sent the data into Zabbix
	if ($line =~ /^zone,device/) {
		
		next if ! defined($data);

		open my $zabbix_sender, "| /opt/zabbix/bin/zabbix_sender -c /opt/zabbix/etc/zabbix_agentd.conf -T -i - >/dev/null" or die "Can't execute zabbix_sender: $!\n";
		print $zabbix_sender $data;
		close $zabbix_sender;

		$data = undef;
	} else {
		
		$date = time(); 
		
		my @parsed = split(/,/, $line);

		my $zone = $parsed[0];
		my $device = $parsed[1];
		my $reads = $parsed[2];
		my $writes = $parsed[3];
		my $read_bytes = $parsed[4];
		my $written_bytes = $parsed[5];

		$data .= "$zone vm.disk.io[$device,reads] $date $reads\n";	
		$data .= "$zone vm.disk.io[$device,writes] $date $writes\n";	
		$data .= "$zone vm.disk.io[$device,read] $date $read_bytes\n";	
		$data .= "$zone vm.disk.io[$device,written] $date $written_bytes";	
	}
}
