#!/usr/bin/env python

import json
import subprocess
import re

command = ('vmadm list -Hpo uuid,type,alias')

regex = r'^(.*):(.*):(.*)$'

p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

array = []

data = {}
zone = {}

for line in p.stdout.readlines():
        
        line = line.rstrip()

        zone['{#UUID}'] = re.match(regex, line).group(1)
        zone['{#ALIAS}'] = re.match(regex, line).group(3)
       	zone['{#UUID_SHORT}'] = re.match(regex, line).group(1).split("-")[0];
       	zone['{#TYPE}'] = re.match(regex, line).group(2)


        array.append(zone)

        zone = {}

data['data'] = array

print json.dumps(data, sort_keys=True, indent=4, separators=(',', ': '))
