#!/usr/bin/env python

import json
import subprocess
import re

command1 = ('dladm show-vnic -po zone,link')
command2 = ('vmadm list -Hpo uuid,alias')

regex = u'^(.*):(.*)$'

p = subprocess.Popen(command1, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

array = []

data = {}
zone = {}

for line in p.stdout.readlines():
        
        line = line.rstrip()

	uuid = re.match(regex, line).group(1)
	iface = re.match(regex, line).group(2)

        zone['{#UUID}'] = uuid 
	zone['{#NETIF}'] = iface 

        array.append(zone)

        zone = {}

p = subprocess.Popen(command2, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

for line in p.stdout.readlines():
        
        line = line.rstrip()

	uuid = re.match(regex, line).group(1)
	alias = re.match(regex, line).group(2)

	for i in range(0, len(array)):
		if uuid == array[i]['{#UUID}']:
			array[i]['{#ALIAS}'] = alias
			#print array[i] 

data['data'] = array

print json.dumps(data, sort_keys=True, indent=4, separators=(',', ': '))
