---
pdnsconfd_source:
  repo: "https://github.com/erigones/pgconfgen.git"
  version: "{{ pdnsconfd_branch | default('master') }}"

pdnsconfd_user: pdns-confd
pdnsconfd_group: pdns-confd
pdnsconfd_uid: 1002
pdnsconfd_gid: 1002
pdnsconfd_shell: /usr/bin/false

pdnsconfd_home: /opt/pdns-confd

pdnsconfd_conf: /opt/local/etc/pdns-confd.ini

pdnsconfd_dependencies:
    - py37-virtualenv
    - git
    - gcc7

# these vars are present in other pdns-* roles, no need to redefine
#pdns_group: pdns
#pdns_recursor_group: pdns-recursor
#pdns_include_dir: /opt/local/etc/pdns.conf.d
#recursor_setgid: "pdns-recursor"
#recursor_include_dir: /opt/local/etc/recursor.conf.d
#recursor_forward_zones_file: "{{ recursor_include_dir }}/forward.zones"
#dnsdist_group: dnsdist
#dnsdist_include_dir: /opt/local/etc/dnsdist.conf.d
#dnsdist_recurse_nets_file: "{{ dnsdist_include_dir }}/50-recursion-subnets.conf"
