- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check

- name: Create virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/base-lx-debian-9.yml
  pre_tasks:
    - include: tasks/build/cleanup.yml
    - include: tasks/build/prepare-base-image.yml
  roles:
    - smartos-vm
  tasks:
    - include: tasks/build/lx/register-host.yml
        hostname=base-lx-debian-9 python_path=/usr/bin/python3

- name: Install and configure appliance
  hosts: base-lx-debian-9
  gather_facts: true
  #vars_files:
  #  - vars/build/os/base-lx-debian-9.yml
  roles:
    - os-common
    - rc-scripts
#x   - zabbix-agent  # copy role to debian
  tasks:
   - include: tasks/build/debian/lx-kickstart.yml
  post_tasks:
    - name: Prepare virtual machine for snapshotting
      shell: prepare-image

- name: Create and save image
  hosts: buildnode
  vars_files:
    - vars/build/vm/base-lx-debian-9.yml
  tasks:
   - include: tasks/build/lx/create-image.yml
