- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check

- name: Create virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/contrib-odoo.yml
  pre_tasks:
    - include: tasks/build/cleanup.yml
    - include: tasks/build/prepare-base-image.yml
  roles:
    - smartos-vm
  tasks:
    - include: tasks/build/lx/register-host.yml
        hostname=contrib-odoo python_path=/usr/bin/python3

- name: Install and configure appliance
  hosts: contrib-odoo
  gather_facts: true
  vars_files:
    - vars/build/os/contrib-odoo.yml
  roles:
    - odoo
    #- zabbix-agent  # 2DO: adapt role to debian
  post_tasks:
    - name: Prepare virtual machine for snapshotting
      shell: prepare-image

- name: Create and save image
  hosts: buildnode
  vars_files:
    - vars/build/vm/contrib-odoo.yml
  tasks:
   - include: tasks/build/lx/create-image.yml
