- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check

- name: Create virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/contrib-centos-7-desktop.yml
  pre_tasks:
    - include: tasks/build/cleanup.yml
    - include: tasks/build/prepare-base-image.yml
  roles:
    - smartos-vm
  tasks:
    - include: tasks/build/centos/register-host.yml
        hostname=contrib-centos-7-desktop

- name: Install and configure appliance
  hosts: contrib-centos-7-desktop
  gather_facts: true
  vars_files:
    - vars/build/os/contrib-centos-7-desktop.yml
  roles:
    - selinux
    - serial-getty
    - zabbix-agent
    - cloud-init
    - rc-scripts
    - mdata-client
    - qemu-guest-agent
    - passwords
    - contrib-centos-7-desktop
    - vm-image

- name: Create and save image
  hosts: buildnode
  vars_files:
    - vars/build/vm/contrib-centos-7-desktop.yml
    - vars/build/os/contrib-centos-7-desktop.yml
  vars:
    image_tags: {internal: false, resize: true, deploy: false}
  tasks:
    - include: tasks/build/centos/create-image.yml
