# Example usage: env EXTRA_VARS="appliance_name=esdc-dns src_version=latest version=v4.3" gmake vm-optlocal
# appliance_name must be specified in cmd line

- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check

- name: Create virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/archive-vm-optlocal.yml
  pre_tasks:
    - include: tasks/build/cleanup.yml
    - include: tasks/build/prepare-base-image.yml

- name: Create local archive
  hosts: buildnode
  gather_facts: false
  vars_files:
    - vars/build/vm/archive-vm-optlocal.yml
  tasks:
    - include: tasks/build/zone/download-vm-optlocal.yml

