- name: Check builder host
  hosts: builder
  tasks:
    - include: tasks/build/check.yml
      when: skip_check is not defined or not skip_check

- name: Create virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/archive-monitoring.yml
  pre_tasks:
    - include: tasks/build/cleanup.yml
    - include: tasks/build/prepare-base-image.yml
  roles:
    - smartos-vm
  tasks:
    - include: tasks/build/zone/register-host.yml
        hostname=archive-monitoring

- name: Create monitoring archive
  hosts: archive-monitoring
  gather_facts: false
  vars_files:
    - vars/build/os/archive-monitoring.yml
  tasks:
    - include: tasks/build/archives/deploy-local-archive.yml
    - include: tasks/build/archives/create-monitoring-archive.yml

- name: Monitoring archive post-build tasks
  hosts: builder
  vars_files:
    - vars/build/os/archive-monitoring.yml
  tasks:
    - include: tasks/build/save-package.yml

- name: Cleanup virtual machine
  hosts: buildnode
  vars_files:
    - vars/build/vm/archive-monitoring.yml
  tasks:
    - include: tasks/build/cleanup.yml
